version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/operator/"
    labels:
      - "go"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/operator/"
    labels:
      - "docker"
      - "area/dependency"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "docker"
      include: "scope"
