---
# Source: istio/templates/istio-operator.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: default
  name: default-operator
spec:
  hub: eu.gcr.io/kyma-project/external/istio
  tag: 1.16.1-distroless
  profile: default
  components:
    cni:
      enabled: true
      k8s:
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
    egressGateways:
    - enabled: false
      k8s:
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 120Mi
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          - resource:
              name: memory
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 0
      name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        podAnnotations:
          reconciler.kyma-project.io/managed-by-reconciler-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
        serviceAnnotations:
          reconciler.kyma-project.io/managed-by-reconciler-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
        env:
        - name: PILOT_HTTP10
          value: "1"
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    defaultProviders:
      tracing: []
    enablePrometheusMerge: false
    enableTracing: true
    extensionProviders:
    - name: kyma-traces
      opencensus:
        context:
        - W3C_TRACE_CONTEXT
        port: 55678
        service: telemetry-trace-collector-internal.kyma-system.svc.cluster.local
    - envoyFileAccessLog:
        logFormat:
          labels: {}
        path: /dev/stdout
      name: envoy
    - envoyFileAccessLog:
        logFormat:
          labels: {}
        path: /dev/stdout
      name: stdout-json
    trustDomain: cluster.local
  values:
    global:
        imagePullPolicy: IfNotPresent
        priorityClassName: kyma-system-priority
        proxy:
          readinessFailureThreshold: 40
          readinessInitialDelaySeconds: 5
          readinessPeriodSeconds: 5
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
        proxy_init:
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
    cni:
        cniBinDir: /opt/cni/bin
        cniConfDir: /etc/cni/net.d
    pilot:
        null
    sidecarInjectorWebhook:
        enableNamespacesByDefault: false
        objectSelector:
          autoInject: true
          enabled: false
        rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        name: istio-ingressgateway
        autoscaleEnabled: true
        podAnnotations:
          reconciler.kyma-project.io/managed-by-reconciler-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
        serviceAnnotations:
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: "*."
          reconciler.kyma-project.io/managed-by-reconciler-disclaimer: |
            DO NOT EDIT - This resource is managed by Kyma.
            Any modifications are discarded and the resource is reverted to the original state.
