apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: istio-operator.kyma-project.io
    app.kubernetes.io/created-by: istio
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: istio
  name: istio-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
