apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: istio-operator.kyma-project.io
    app.kubernetes.io/created-by: istio
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: istio
    control-plane: controller-manager
  name: istio-controller-manager-metrics-service
  namespace: istio-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: istio-operator.kyma-project.io
    control-plane: controller-manager
